### ISSUE TITLE
Verbindung Web zu JSON

### ISSUE THREAD

**Issue by JanH8** [KAPU-Vertretung/Web#1]
Schwieriger als gedacht.

**Comment by JanH8** [comment]
Grundsätzlich läuft es. Mir fehlt allerdings die Vertretungsstunde beziehungsweise der Text "Studienzeit" etc in der JSON Datei @KAPU-Vertretung/backend

**Comment by JanH8** [comment]
Frage: Wie ist das geplant wenn eine Klasse mehrfache Vertretungen am Tag hat? Dann taucht der Key doch mehrfach auf oder? Das habe ich mit dem neusten commit noch nicht berücksichtigt. @Nikos410

**Comment by Nikos410** [comment]
@JanH8
Nein, jede Klasse taucht nur einmal auf (oder keinmal, wenn sie keine Vertretung hat). Wenn eine Klasse mehrere Vertretungen hat enthält das Array mehrere Objekte, jedes entspricht einer "Vertretung"

**Comment by JanH8** [comment]
Kannst du den Fall in die Beispieldatei einbauen?

**Comment by JanH8** [comment]
Läuft :)
